version: '{build}'
image: Visual Studio 2017
build_script:
  - ps: $env:VersionSuffix = 'pdb' + [int]::Parse($env:appveyor_build_number).ToString('000')
  - cd csharp && build_packages.bat
artifacts:
  - path: '**\*.nupkg'